pub const ADJECTIVES: &'static [&'static str] = &[
    "able", "abnorma", "again", "airexpl", "ang", "anger", "asail", "attack", "aurora", "awl",
    "ban", "band", "bare", "beat", "beated", "belly", "bind", "bite", "bloc", "blood", "body",
    "book", "breath", "bump", "cast", "cham", "clamp", "clap", "claw", "clear", "cli", "clip",
    "cloud", "contro", "convy", "coolhit", "crash", "cry", "cut", "descri", "d-fight", "dig",
    "ditch", "div", "doz", "dre", "dul", "du-pin", "dye", "earth", "edu", "eg-bomb", "egg",
    "elegy", "ele-hit", "embody", "empli", "engl", "erupt", "evens", "explor", "eyes", "fall",
    "fast", "f-car", "f-dance", "fears", "f-fight", "fight", "fir", "fire", "firehit", "flame",
    "flap", "flash", "flew", "force", "fra", "freeze", "frog", "g-bird", "genkiss", "gift",
    "g-kiss", "g-mouse", "grade", "grow", "hammer", "hard", "hat", "hate", "h-bomb", "hell-r",
    "hemp", "hint", "hit", "hu", "hunt", "hypnosi", "inha", "iro", "ironbar", "ir-wing", "j-gun",
    "kee", "kick", "knif", "knife", "knock", "level", "ligh", "lighhit", "light", "live", "l-wall",
    "mad", "majus", "mel", "melo", "mess", "milk", "mimi", "miss", "mixing", "move", "mud",
    "ni-bed", "noisy", "noonli", "null", "n-wave", "pat", "peace", "pin", "plan", "plane", "pois",
    "pol", "powde", "powe", "power", "prize", "protect", "proud", "rage", "recor", "reflac",
    "refrec", "regr", "reliv", "renew", "r-fight", "ring", "rkick", "rock", "round", "rus", "rush",
    "sand", "saw", "scissor", "scra", "script", "seen", "server", "shadow", "shell", "shine",
    "sho", "sight", "sin", "small", "smelt", "smok", "snake", "sno", "snow", "sou", "so-wave",
    "spar", "spec", "spid", "s-pin", "spra", "stam", "stare", "stea", "stone", "storm", "stru",
    "strug", "studen", "subs", "sucid", "sun-lig", "sunris", "suply", "s-wave", "tails", "tangl",
    "taste", "telli", "thank", "tonkick", "tooth", "torl", "train", "trikick", "tunge", "volt",
    "wa-gun", "watch", "wave", "w-bomb", "wfall", "wfing", "whip", "whirl", "wind", "wolf", "wood",
    "wor", "yuja",
];

pub const NOUNS: &'static [&'static str] = &[
    "seed", "grass", "flowe", "shad", "cabr", "snake", "gold", "cow", "guiki", "pedal", "delan",
    "b-fly", "bide", "keyu", "fork", "lap", "pige", "pijia", "caml", "lat", "bird", "baboo", "viv",
    "aboke", "pikaq", "rye", "san", "bread", "lidel", "lide", "pip", "pikex", "rok", "jugen",
    "pud", "bude", "zhib", "gelu", "gras", "flow", "laful", "ath", "bala", "corn", "moluf", "desp",
    "daked", "mimi", "bolux", "koda", "gelud", "monk", "sumoy", "gedi", "wendi", "nilem", "nile",
    "nilec", "kezi", "yongl", "hude", "wanli", "geli", "guail", "madaq", "wuci", "wuci", "mujef",
    "jelly", "sicib", "gelu", "neluo", "boli", "jiale", "yed", "yede", "clo", "scare", "aoco",
    "dede", "dedei", "bawu", "jiug", "badeb", "badeb", "hole", "balux", "ges", "fant", "quar",
    "yihe", "swab", "slipp", "clu", "depos", "biliy", "yuano", "some", "no", "yela", "empt",
    "zecun", "xiahe", "bolel", "deji", "macid", "xihon", "xito", "luck", "menji", "gelu", "deci",
    "xide", "dasaj", "dongn", "ricul", "minxi", "baliy", "zenda", "luzel", "hele5", "0fenb",
    "kail", "jiand", "carp", "jinde", "lapu", "mude", "yifu", "linli", "sandi", "husi", "jinc",
    "oumu", "oumux", "cap", "kuiza", "pud", "tiao", "frman", "clau", "spark", "drago", "boliu",
    "guail", "miyou", "miy", "qiaok", "beil", "mukei", "rided", "madam", "bagep", "croc", "alige",
    "oudal", "oud", "dada", "hehe", "yedea", "nuxi", "nuxin", "rouy", "aliad", "stick", "qiang",
    "laand", "piqi", "pi", "pupi", "deke", "dekej", "nadi", "nadio", "mali", "pea", "elect",
    "flowe", "mal", "mali", "hushu", "nilee", "yuzi", "popoz", "duzi", "heba", "xian", "shan",
    "yeyea", "wuy", "luo", "kefe", "hula", "crow", "yadeh", "mow", "annan", "suoni", "kyli",
    "hulu", "hudel", "yehe", "gulae", "yehe", "blu", "gelan", "boat", "nip", "poit", "helak",
    "xinl", "bear", "linb", "mageh", "magej", "wuli", "yide", "rive", "fish", "aogu", "delie",
    "mante", "konmu", "delu", "helu", "huan", "huma", "dongf", "jinca", "hede", "defu", "liby",
    "jiapa", "meji", "hele", "buhu", "milk", "habi", "thun", "gard", "don", "yangq", "sanaq",
    "banq", "luj", "phix", "siei", "egg",
];
